name: autorepositioning_scrollview
description: A ScrollView that can re-position itself according to initial parameters and during use when tilting the device.
version: 1.0.0
homepage: https://github.com/TheCarpetMerchant/autorepositioning_scrollview

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

